export const banderaPais = {
    "Afghanistan": "🇦🇫",
    "Åland": "🇦🇽",
    "Albania": "🇦🇱",
    "Germany": "🇩🇪",
    "Andorra": "🇦🇩",
    "Angola": "🇦🇴",
    "Eel": "🇦🇮",
    "Antarctica": "🇦🇶",
    "Antigua and Barbuda": "🇦🇬",
    "Saudi Arabia": "🇸🇦",
    "Algeria": "🇩🇿",
    "Argentina": "🇦🇷",
    "Armenia": "🇦🇲",
    "Aruba": "🇦🇼",
    "Australia": "🇦🇺",
    "Austria": "🇦🇹",
    "Azerbaijan": "🇦🇿",
    "Bahamas": "🇧🇸",
    "Bahrain": "🇧🇭",
    "Bangladesh": "🇧🇩",
    "Barbados": "🇧🇧",
    "Belgium": "🇧🇪",
    "Belize": "🇧🇿",
    "Benin": "🇧🇯",
    "Bermuda": "🇧🇲",
    "Belarus": "🇧🇾",
    "Bolivia": "🇧🇴",
    "Bosnia and Herzegovina": "🇧🇦",
    "Botswana": "🇧🇼",
    "Brazil": "🇧🇷",
    "Brunei": "🇧🇳",
    "Bulgaria": "🇧🇬",
    "Burkina": "🇧🇫",
    "Burundi": "🇧🇮",
    "Bhutan": "🇧🇹",
    "Cape Verde": "🇨🇻",
    "Cambodia": "🇰🇭",
    "Cameroon": "🇨🇲",
    "Canada": "🇨🇦",
    "Caribbean Dutch": "🇧🇶",
    "Qatar": "🇶🇦",
    "Chad": "🇹🇩",
    "Czech Republic": "🇨🇿",
    "Chile": "🇨🇱",
    "China": "🇨🇳",
    "Cyprus": "🇨🇾",
    "Vatican City": "🇻🇦",
    "Colombia": "🇨🇴",
    "Comoros": "🇰🇲",
    "Congo": "🇨🇬",
    "Congo (Dem. Rep.)": "🇨🇩",
    "North Korea": "🇰🇵",
    "South Korea": "🇰🇷",
    "Ivory Coast": "🇨🇮",
    "Costa Rica": "🇨🇷",
    "Croatia": "🇭🇷",
    "Cuba": "🇨🇺",
    "Curacao": "🇨🇼",
    "Denmark": "🇩🇰",
    "Djibouti": "🇩🇯",
    "Dominica": "🇩🇲",
    "Ecuador": "🇪🇨",
    "Egypt": "🇪🇬",
    "El Salvador": "🇸🇻",
    "United Arab Emirates": "🇦🇪",
    "Eritrea": "🇪🇷",
    'Scotland': "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    "Slovenia": "🇸🇮",
    "Spain": "🇪🇸",
    "United States of America": "🇺🇸",
    "Estonia": "🇪🇪",
    "Ethiopia": "🇪🇹",
    "Philippines": "🇵🇭",
    "Finland": "🇫🇮",
    "Fiji": "🇫🇯",
    "France": "🇫🇷",
    "Gabon": "🇬🇦",
    'Wales': "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    "Gambia": "🇬🇲",
    "Georgia": "🇬🇪",
    "Ghana": "🇬🇭",
    "Gibraltar": "🇬🇮",
    "Greece": "🇬🇷",
    "Granada": "🇬🇩",
    "Greenland": "🇬🇱",
    "Guadalupe": "🇬🇵",
    "Guam": "🇬🇺",
    "Guatemala": "🇬🇹",
    "French Guiana": "🇬🇫",
    "Guernsey": "🇬🇬",
    "Guinea": "🇬🇳",
    "Equatorial Guinea": "🇬🇶",
    "Guinea-Bissau": "🇬🇼",
    "Guyana": "🇬🇾",
    "Haiti": "🇭🇹",
    "Honduras": "🇭🇳",
    "Hong Kong": "🇭🇰",
    "Hungary": "🇭🇺",
    "India": "🇮🇳",
    "Indonesia": "🇮🇩",
    'England': "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    "Iraq": "🇮🇶",
    "Iran": "🇮🇷",
    "Ireland": "🇮🇪",
    "Bouvet Island": "🇧🇻",
    "Isle of Man": "🇮🇲",
    "Christmas Island": "🇨🇽",
    "Norfolk Island": "🇳🇫",
    "Iceland": "🇮🇸",
    "Cayman Islands": "🇰🇾",
    "Cocos Islands": "🇨🇨",
    "Cook Islands": "🇨🇰",
    "Faroe Islands": "🇫🇴",
    "South Georgia and the South Sandwich Islands": "🇬🇸",
    "Heard and McDonald Islands": "🇭🇲",
    "Malvinas Islands": "🇫🇰",
    "Northern Mariana Islands": "🇲🇵",
    "Marshall Islands": "🇲🇭",
    "Pitcairn Islands": "🇵🇳",
    "Solomon Islands": "🇸🇧",
    "Svalbard and Jan Mayen": "🇸🇯",
    "Tokelau": "🇹🇰",
    "Turks and Caicos Islands": "🇹🇨",
    "United States Minor Outlying Islands": "🇺🇲",
    "United States Virgin Islands": "🇻🇮",
    "British Virgin Islands": "🇻🇬",
    "Israel": "🇮🇱",
    "Italy": "🇮🇹",
    "Jamaica": "🇯🇲",
    "Japan": "🇯🇵",
    "Jersey": "🇯🇪",
    "Jordan": "🇯🇴",
    "Kazakhstan": "🇰🇿",
    "Kenya": "🇰🇪",
    "Kyrgyzstan": "🇰🇬",
    "Kiribati": "🇰🇮",
    "Kosovo": "🇽🇰",
    "Kuwait": "🇰🇼",
    "Laos": "🇱🇦",
    "Lesotho": "🇱🇸",
    "Latvia": "🇱🇻",
    "Lebanon": "🇱🇧",
    "Liberia": "🇱🇷",
    "Libya": "🇱🇾",
    "Liechtenstein": "🇱🇮",
    "Lithuania": "🇱🇹",
    "Luxembourg": "🇱🇺",
    "Macao": "🇲🇴",
    "North Macedonia": "🇲🇰",
    "Madagascar": "🇲🇬",
    "Malaysia": "🇲🇾",
    "Malawi": "🇲🇼",
    "Maldives": "🇲🇻",
    "Mali": "🇲🇱",
    "Malta": "🇲🇹",
    "Morocco": "🇲🇦",
    "Martinique": "🇲🇶",
    "Mauricio": "🇲🇺",
    "Mauritania": "🇲🇷",
    "Mayotte": "🇾🇹",
    "Mexico": "🇲🇽",
    "Micronesia": "🇫🇲",
    "Moldova": "🇲🇩",
    "Monaco": "🇲🇨",
    "Mongolia": "🇲🇳",
    "Montenegro": "🇲🇪",
    "Montserrat": "🇲🇸",
    "Mozambique": "🇲🇿",
    "Myanmar": "🇲🇲",
    "Namibia": "🇳🇦",
    "Nauru": "🇳🇷",
    "Nepal": "🇳🇵",
    "Nicaragua": "🇳🇮",
    "Niger": "🇳🇪",
    "Nigeria": "🇳🇬",
    "Niue": "🇳🇺",
    "Norway": "🇳🇴",
    "New Caledonia": "🇳🇨",
    "New Zealand": "🇳🇿",
    "Oman": "🇴🇲",
    "Netherlands": "🇳🇱",
    "Pakistan": "🇵🇰",
    "Palau": "🇵🇼",
    "Palestine": "🇵🇸",
    "Panama": "🇵🇦",
    "Papua New Guinea": "🇵🇬",
    "Paraguay": "🇵🇾",
    "Peru": "🇵🇪",
    "French Polynesia": "🇵🇫",
    "Poland": "🇵🇱",
    "Portugal": "🇵🇹",
    "Puerto Rico": "🇵🇷",
    "United Kingdom": "🇬🇧",
    "Central African Republic": "🇨🇫",
    "South Africa": "🇿🇦",
    "Dominican Republic": "🇩🇴",
    "Slovakia": "🇸🇰",
    "Meeting": "🇷🇪",
    "Rwanda": "🇷🇼",
    "Romania": "🇷🇴",
    "Russia": "🇷🇺",
    "Western Sahara": "🇪🇭",
    "Saint Martin (France)": "🇲🇫",
    "Samoa": "🇼🇸",
    "American Samoa": "🇦🇸",
    "Saint Bartholomew": "🇧🇱",
    "Saint Kitts and Nevis": "🇰🇳",
    "San Marino": "🇸🇲",
    "Saint Pierre and Miquelon": "🇵🇲",
    "Saint Vincent and the Grenadines": "🇻🇨",
    "Saint Helena, Ascension and Tristan da Cunha": "🇸🇭",
    "Saint Lucia": "🇱🇨",
    "Sao Tome and Principe": "🇸🇹",
    "Senegal": "🇸🇳",
    "Serbia": "🇷🇸",
    "Seychelles": "🇸🇨",
    "Sierra Leone": "🇸🇱",
    "Singapore": "🇸🇬",
    "Saint Martin (Netherlands)": "🇸🇽",
    "Syria": "🇸🇾",
    "Somalia": "🇸🇴",
    "Sri Lanka": "🇱🇰",
    "Swaziland": "🇸🇿",
    "Sudan": "🇸🇩",
    "South Sudan": "🇸🇸",
    "Sweden": "🇸🇪",
    "Switzerland": "🇨🇭",
    "Suriname": "🇸🇷",
    "Thailand": "🇹🇭",
    "Taiwan": "🇹🇼",
    "Tanzania": "🇹🇿",
    "Tajikistan": "🇹🇯",
    "British Indian Ocean Territory": "🇮🇴",
    "French Southern and Antarctic Lands": "🇹🇫",
    "East Timor": "🇹🇱",
    "Togo": "🇹🇬",
    "Tonga": "🇹🇴",
    "Trinidad and Tobago": "🇹🇹",
    "Tunisia": "🇹🇳",
    "Turkmenistan": "🇹🇲",
    "Turkey": "🇹🇷",
    "Tuvalu": "🇹🇻",
    "Ukraine": "🇺🇦",
    "Uganda": "🇺🇬",
    "Uruguay": "🇺🇾",
    "Uzbekistan": "🇺🇿",
    "Vanuatu": "🇻🇺",
    "Venezuela": "🇻🇪",
    "Vietnam": "🇻🇳",
    "Wallis and Futuna": "🇼🇫",
    "Yemen": "🇾🇪",
    "Zambia": "🇿🇲",
    "Zimbabwe": "🇿🇼"
};

Object.freeze(banderaPais);

// VERSIÓN ORIGINAL ESPAÑOLA:

// "Afganistán": "🇦🇫",
// "Åland": "🇦🇽",
// "Albania": "🇦🇱",
// "Alemania": "🇩🇪",
// "Andorra": "🇦🇩",
// "Angola": "🇦🇴",
// "Anguila": "🇦🇮",
// "Antártida": "🇦🇶",
// "Antigua y Barbuda": "🇦🇬",
// "Arabia Saudita": "🇸🇦",
// "Argelia": "🇩🇿",
// "Argentina": "🇦🇷",
// "Armenia": "🇦🇲",
// "Aruba": "🇦🇼",
// "Australia": "🇦🇺",
// "Austria": "🇦🇹",
// "Azerbaiyán": "🇦🇿",
// "Bahamas": "🇧🇸",
// "Baréin": "🇧🇭",
// "Bangladesh": "🇧🇩",
// "Barbados": "🇧🇧",
// "Bélgica": "🇧🇪",
// "Belice": "🇧🇿",
// "Benín": "🇧🇯",
// "Bermudas": "🇧🇲",
// "Bielorrusia": "🇧🇾",
// "Bolivia": "🇧🇴",
// "Bosnia y Herzegovina": "🇧🇦",
// "Botsuana": "🇧🇼",
// "Brasil": "🇧🇷",
// "Brunéi": "🇧🇳",
// "Bulgaria": "🇧🇬",
// "Burkina": "🇧🇫",
// "Burundi": "🇧🇮",
// "Bután": "🇧🇹",
// "Cabo Verde": "🇨🇻",
// "Camboya": "🇰🇭",
// "Camerún": "🇨🇲",
// "Canadá": "🇨🇦",
// "Caribe Neerlandés": "🇧🇶",
// "Catar": "🇶🇦",
// "Chad": "🇹🇩",
// "República Checa": "🇨🇿",
// "Chile": "🇨🇱",
// "China": "🇨🇳",
// "Chipre": "🇨🇾",
// "Ciudad del Vaticano": "🇻🇦",
// "Colombia": "🇨🇴",
// "Comoras": "🇰🇲",
// "Congo": "🇨🇬",
// "Congo (Rep. Dem.)": "🇨🇩",
// "Corea del Norte": "🇰🇵",
// "Corea del Sur": "🇰🇷",
// "Costa de Marfil": "🇨🇮",
// "Costa Rica": "🇨🇷",
// "Croacia": "🇭🇷",
// "Cuba": "🇨🇺",
// "Curazao": "🇨🇼",
// "Dinamarca": "🇩🇰",
// "Yibuti": "🇩🇯",
// "Dominica": "🇩🇲",
// "Ecuador": "🇪🇨",
// "Egipto": "🇪🇬",
// "El Salvador": "🇸🇻",
// "Emiratos Árabes Unidos": "🇦🇪",
// "Eritrea": "🇪🇷",
// "Escocia": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
// "Eslovenia": "🇸🇮",
// "España": "🇪🇸",
// "Estados Unidos de América": "🇺🇸",
// "Estonia": "🇪🇪",
// "Etiopía": "🇪🇹",
// "Filipinas": "🇵🇭",
// "Finlandia": "🇫🇮",
// "Fiyi": "🇫🇯",
// "Francia": "🇫🇷",
// "Gabón": "🇬🇦",
// "Gales": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
// "Gambia": "🇬🇲",
// "Georgia": "🇬🇪",
// "Ghana": "🇬🇭",
// "Gibraltar": "🇬🇮",
// "Grecia": "🇬🇷",
// "Granada": "🇬🇩",
// "Groenlandia": "🇬🇱",
// "Guadalupe": "🇬🇵",
// "Guam": "🇬🇺",
// "Guatemala": "🇬🇹",
// "Guayana Francesa": "🇬🇫",
// "Guernsey": "🇬🇬",
// "Guinea": "🇬🇳",
// "Guinea Ecuatorial": "🇬🇶",
// "Guinea-Bisáu": "🇬🇼",
// "Guyana": "🇬🇾",
// "Haití": "🇭🇹",
// "Honduras": "🇭🇳",
// "Hong Kong": "🇭🇰",
// "Hungría": "🇭🇺",
// "India": "🇮🇳",
// "Indonesia": "🇮🇩",
// "Inglaterra": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
// "Irak": "🇮🇶",
// "Irán": "🇮🇷",
// "Irlanda": "🇮🇪",
// "Isla Bouvet": "🇧🇻",
// "Isla de Man": "🇮🇲",
// "Isla de Navidad": "🇨🇽",
// "Isla Norfolk": "🇳🇫",
// "Islandia": "🇮🇸",
// "Islas Caimán": "🇰🇾",
// "Islas Cocos": "🇨🇨",
// "Islas Cook": "🇨🇰",
// "Islas Feroe": "🇫🇴",
// "Islas Georgias del Sur y Sándwich del Sur": "🇬🇸",
// "Islas Heard y McDonald": "🇭🇲",
// "Islas Malvinas": "🇫🇰",
// "Islas Marianas del Norte": "🇲🇵",
// "Islas Marshall": "🇲🇭",
// "Islas Pitcairn": "🇵🇳",
// "Islas Salomón": "🇸🇧",
// "Svalbard y Jan Mayen": "🇸🇯",
// "Tokelau": "🇹🇰",
// "Islas Turcas y Caicos": "🇹🇨",
// "Islas Ultramarinas Menores de los Estados Unidos": "🇺🇲",
// "Islas Vírgenes de los Estados Unidos": "🇻🇮",
// "Islas Vírgenes Británicas": "🇻🇬",
// "Israel": "🇮🇱",
// "Italia": "🇮🇹",
// "Jamaica": "🇯🇲",
// "Japón": "🇯🇵",
// "Jersey": "🇯🇪",
// "Jordania": "🇯🇴",
// "Kazajistán": "🇰🇿",
// "Kenia": "🇰🇪",
// "Kirguistán": "🇰🇬",
// "Kiribati": "🇰🇮",
// "Kosovo": "🇽🇰",
// "Kuwait": "🇰🇼",
// "Laos": "🇱🇦",
// "Lesoto": "🇱🇸",
// "Letonia": "🇱🇻",
// "Líbano": "🇱🇧",
// "Liberia": "🇱🇷",
// "Libia": "🇱🇾",
// "Liechtenstein": "🇱🇮",
// "Lituania": "🇱🇹",
// "Luxemburgo": "🇱🇺",
// "Macao": "🇲🇴",
// "Macedonia del Norte": "🇲🇰",
// "Madagascar": "🇲🇬",
// "Malasia": "🇲🇾",
// "Malawi": "🇲🇼",
// "Maldivas": "🇲🇻",
// "Malí": "🇲🇱",
// "Malta": "🇲🇹",
// "Marruecos": "🇲🇦",
// "Martinica": "🇲🇶",
// "Mauricio": "🇲🇺",
// "Mauritania": "🇲🇷",
// "Mayotte": "🇾🇹",
// "México": "🇲🇽",
// "Micronesia": "🇫🇲",
// "Moldavia": "🇲🇩",
// "Mónaco": "🇲🇨",
// "Mongolia": "🇲🇳",
// "Montenegro": "🇲🇪",
// "Montserrat": "🇲🇸",
// "Mozambique": "🇲🇿",
// "Myanmar": "🇲🇲",
// "Namibia": "🇳🇦",
// "Nauru": "🇳🇷",
// "Nepal": "🇳🇵",
// "Nicaragua": "🇳🇮",
// "Níger": "🇳🇪",
// "Nigeria": "🇳🇬",
// "Niue": "🇳🇺",
// "Noruega": "🇳🇴",
// "Nueva Caledonia": "🇳🇨",
// "Nueva Zelanda": "🇳🇿",
// "Omán": "🇴🇲",
// "Países Bajos": "🇳🇱",
// "Pakistán": "🇵🇰",
// "Palaos": "🇵🇼",
// "Palestina": "🇵🇸",
// "Panamá": "🇵🇦",
// "Papúa Nueva Guinea": "🇵🇬",
// "Paraguay": "🇵🇾",
// "Perú": "🇵🇪",
// "Polinesia Francesa": "🇵🇫",
// "Polonia": "🇵🇱",
// "Portugal": "🇵🇹",
// "Puerto Rico": "🇵🇷",
// "Reino Unido": "🇬🇧",
// "República Centroafricana": "🇨🇫",
// "Sudáfrica": "🇿🇦",
// "República Dominicana": "🇩🇴",
// "Eslovaquia": "🇸🇰",
// "Reunión": "🇷🇪",
// "Ruanda": "🇷🇼",
// "Rumania": "🇷🇴",
// "Rusia": "🇷🇺",
// "Sahara Occidental": "🇪🇭",
// "San Martín (Francia)": "🇲🇫",
// "Samoa": "🇼🇸",
// "Samoa Americana": "🇦🇸",
// "San Bartolomé": "🇧🇱",
// "San Cristóbal y Nieves": "🇰🇳",
// "San Marino": "🇸🇲",
// "San Pedro y Miquelón": "🇵🇲",
// "San Vicente y las Granadinas": "🇻🇨",
// "Santa Elena, Ascensión y Tristán de Acuña": "🇸🇭",
// "Santa Lucía": "🇱🇨",
// "Santo Tomé y Príncipe": "🇸🇹",
// "Senegal": "🇸🇳",
// "Serbia": "🇷🇸",
// "Seychelles": "🇸🇨",
// "Sierra Leona": "🇸🇱",
// "Singapur": "🇸🇬",
// "San Martín (Países Bajos)": "🇸🇽",
// "Siria": "🇸🇾",
// "Somalia": "🇸🇴",
// "Sri Lanka": "🇱🇰",
// "Suazilandia": "🇸🇿",
// "Sudán": "🇸🇩",
// "Sudán del Sur": "🇸🇸",
// "Suecia": "🇸🇪",
// "Suiza": "🇨🇭",
// "Surinam": "🇸🇷",
// "Tailandia": "🇹🇭",
// "Taiwán": "🇹🇼",
// "Tanzania": "🇹🇿",
// "Tayikistán": "🇹🇯",
// "Territorio Británico del Océano Índico": "🇮🇴",
// "Tierras Australes y Antárticas Francesas": "🇹🇫",
// "Timor Oriental": "🇹🇱",
// "Togo": "🇹🇬",
// "Tonga": "🇹🇴",
// "Trinidad y Tobago": "🇹🇹",
// "Túnez": "🇹🇳",
// "Turkmenistán": "🇹🇲",
// "Turquía": "🇹🇷",
// "Tuvalu": "🇹🇻",
// "Ucrania": "🇺🇦",
// "Uganda": "🇺🇬",
// "Uruguay": "🇺🇾",
// "Uzbekistán": "🇺🇿",
// "Vanuatu": "🇻🇺",
// "Venezuela": "🇻🇪",
// "Vietnam": "🇻🇳",
// "Wallis y Futuna": "🇼🇫",
// "Yemen": "🇾🇪",
// "Zambia": "🇿🇲",
// "Zimbabue": "🇿🇼"